project:
  type: website
  output-dir: docs

website:
  title: "Matthew J. Durán"
  navbar:
    background: primary
    search: FALSE
    left:
      - text: "CV"
        href: cv.pdf
      - text: "Projects"
        menu:
          - text: "OCEPTX"
            href: oceptx/index.qmd
format:
  html:
    theme: cosmo
    css: styles2.css
    toc: false

editor: visual

