project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - text: "Home"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

