project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research Archive" 
        href: research.qmd
      - text: "Crime"
        menu:
          - text: "Driving While Intoxicated (DWI)"
            href: dwi-home.qmd


format:
  html:
    theme: cosmo
    css: styles2.css
    toc: false

editor: visual

